[project]
name = "read-aloud-el"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "parakeet-mlx>=0.5.0",
    "sexpdata>=1.0.2",
    "sounddevice>=0.5.5",
    "websocket-bridge-python>=0.0.2",
]
